androidJarPath = example/android-8
parentFolderOfApk = example/App183
apkName = com.a1.quiz.asvab.free.instrumented.apk
loopUnraveledTime = 1
targets = <LoggerLib.Logger: void reportString(java.lang.String,java.lang.String)>@1

# not needed currently but in place for legacy test reasons, likely to be removed in the future
rtJar = C:\\Program Files\\Eclipse Adoptium\\jdk-8.0.452.9-hotspot\\jre\\lib\\rt.jar